#!/bin/sh

echo "Running Checkstyle & Spotless..."

# Save the current index
git stash push --keep-index --include-untracked -m "pre-commit-check"

mvn initialize checkstyle:check spotless:apply
status=$?

# Restore the working tree while keeping the original index
git stash pop --index

if [ $status -ne 0 ]; then
    echo "Spotless/checkstyle failed. Commit aborted."
    exit 1
fi

exit 0
