#!/bin/sh

echo "Running Checkstyle & Spotless..."

mvn initialize checkstyle:check spotless:apply

if [ $? -ne 0 ]; then
    echo "Spotless/checkstyle failed. Commit aborted."
    exit 1
fi

# Stage any files modified by Spotless
git add -A

exit 0
