package lu.kbra.pclib.db.autobuild.dialect;

public enum DbmsCapability {

	TABLE_CHARACTER_SET,
	TABLE_ENGINE,
	COLUMN_ON_UPDATE,
	COLUMN_AUTO_INCREMENT,
	INLINE_PRIMARY_KEY_AUTOINCREMENT,
	QUALIFY_CTE_TABLES_WITH_DATABASE,
	GENERATED_COLUMN_NOT_NULL,
	DATABASE_CHARACTER_SET,
	DATABASE_COLLATION;

}
