name: Deploy Pages

on:
  workflow_dispatch: 
  workflow_run:
    workflows: ["Nightly", "Release"]
    types: [completed]
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PAGES_HOST }}
          username: ${{ secrets.PAGES_USERNAME }}
          key: ${{ secrets.PAGES_SSH_KEY }}
          port: ${{ secrets.PAGES_PORT }}
          script: |
            set -e

            mkdir -p /var/www
            cd /var/www

            git config --global --add safe.directory /var/www/pclib.kbra.lu
            if [ ! -d "pclib.kbra.lu/.git" ]; then
              rm -rf pclib.kbra.lu/*
              rm -rf pclib.kbra.lu/.[!.]* pclib.kbra.lu/..?* 2>/dev/null || true

              git clone \
                --branch pages \
                https://${{ secrets.GH_PAT }}@github.com/UnKabaraQuiDev/PCLib.git \
                "pclib.kbra.lu"
            fi

            cd /var/www/pclib.kbra.lu

            git fetch origin
            git checkout pages
            git reset --hard origin/pages
