name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

jobs:
  release:
    runs-on: self-hosted

    permissions:
      contents: write

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          server-id: nexus.kbra.lu-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Ensure NOT a SNAPSHOT version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Detected version: $VERSION"

          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            echo "Snapshot version detected. Releases must NOT be snapshots."
            exit 1
          fi

      - name: Apply formatting
        run: mvn spotless:apply

      - name: Commit & push if needed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git diff --cached --quiet || git commit -m "[NIGHTLY] Apply code formatting"

          git push

      - name: Build project
        run: mvn -B clean package deploy

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            **/target/*.jar
            !target/*.jar