package lu.kbra.pclib.db.domain.dialect;

public enum DbmsCapability {

	TABLE_CHARACTER_SET,
	TABLE_ENGINE,
	COLUMN_ON_UPDATE,
	COLUMN_AUTO_INCREMENT,
	INLINE_PRIMARY_KEY_AUTOINCREMENT,
	GENERATED_COLUMN_NOT_NULL,
	DATABASE_CHARACTER_SET,
	DATABASE_COLLATION,
	BATCH_INSERT_RETURN_GENERATED_KEYS;

}
